name: json2dart
description: A CLI tool to help generate dart classes from json returned from API
version: 1.1.0
homepage: https://www.github.com/pacifio/json2dart

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  json_ast: ^1.0.5
  args: ^2.2.0
  http: ^0.13.3
  dart_style: ^1.3.13